name=probot
version=0.2.2
author=Tuna Gül
maintainer=Tuna Gül <tunagul54@gmail.com>
sentence=ProBot Library for Robotics Competitions.
paragraph=Includes motor controllers, chassis, encoders, PID control and so much more.
category=Device Control
url=https://github.com/nfrproducts/probot-lib
architectures=esp32
includes=probot.h
depends=Adafruit NeoPixel
