name=probot
version=0.2.9
author=Tuna Gül
maintainer=Tuna Gül <tunagul54@gmail.com>
sentence=Probot Communication Library for ESP32-S3 Robotics.
paragraph=Driver station, WiFi AP, WebSocket joystick, telemetry, and match state management.
category=Device Control
url=https://github.com/nfrproducts/probot-lib
architectures=esp32
includes=probot.h
depends=Adafruit NeoPixel
