site_name: Probot Lib Documentation
site_description: Arduino tabanlı robot kütüphanesi dokümantasyonu.
site_author: Tuna Gül
repo_url: https://github.com/tunapro1234/probot_lib
edit_uri: ""

theme:
  name: material
  palette:
    primary: indigo
    accent: blue

nav:
  - Anasayfa: index.md
  - Örnekler:
      - Blink: examples/RobotBlink.md
  - API Referansı: API.md
  - Katkıda Bulunma: contributing.md
  - Lisans: LICENSE.md

plugins:
  - search

extra:
  generator: false
  language: tr
