title: Probot Lib Documentation
description: Arduino tabanlı robot kütüphanesi dokümantasyonu.
theme: minima
baseurl: "/probot_lib"
url: "https://tunapro1234.github.io"

# Navigation
collections:
  examples:
    output: true
    permalink: /examples/:path/

# Navbar
nav:
  - Anasayfa: index.md
  - Örnekler:
      - Blink: examples/RobotBlink.md
  - API Referansı: API.md
  - Katkıda Bulunma: contributing.md
  - Lisans: LICENSE.md
